// src/pages/Register.tsx
import { useState } from 'react';
import { Leaf, Mail, Lock, User, CheckCircle } from 'lucide-react';
import { Link, useNavigate } from 'react-router';
import { useAuth } from '../contexts/AuthContext';

export default function Register() {
  const navigate = useNavigate();
  const { register } = useAuth();
  const [formData, setFormData] = useState({
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
    role: 'Usuario' as 'Usuario' | 'Administrador',
  });
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    // Validaciones
    if (!formData.name || !formData.email || !formData.password || !formData.confirmPassword) {
      setError('Por favor complete todos los campos');
      return;
    }

    if (formData.password !== formData.confirmPassword) {
      setError('Las contraseñas no coinciden');
      return;
    }

    if (formData.password.length < 6) {
      setError('La contraseña debe tener al menos 6 caracteres');
      return;
    }

    const success = register(formData.name, formData.email, formData.password, formData.role);
    if (success) {
      if (formData.role === 'Administrador') {
        navigate('/admin');
      } else {
        navigate('/');
      }
    } else {
      setError('Error al registrar la cuenta');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#E8F5E9] to-[#C8E6C9] flex items-center justify-center p-6">
      <div className="w-full max-w-md">
        {/* Logo */}
        <Link to="/" className="flex items-center justify-center gap-3 mb-8">
          <div className="w-16 h-16 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-3xl flex items-center justify-center shadow-2xl">
            <Leaf className="w-9 h-9 text-white" />
          </div>
          <span className="text-4xl font-bold bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] bg-clip-text text-transparent">
            EcoLand
          </span>
        </Link>

        {/* Register Card */}
        <div className="bg-white rounded-3xl shadow-2xl p-8 border-2 border-gray-100">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Crear cuenta</h1>
            <p className="text-gray-600">Únete a la comunidad EcoLand</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-5">
            {/* Full Name */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Nombre completo
              </label>
              <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder="Juan Pérez"
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all"
                />
              </div>
            </div>

            {/* Email */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Correo electrónico
              </label>
              <div className="relative">
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="tu@email.com"
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all"
                />
              </div>
            </div>

            {/* Password */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Contraseña
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="password"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  placeholder="Mínimo 6 caracteres"
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all"
                />
              </div>
            </div>

            {/* Confirm Password */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Confirmar contraseña
              </label>
              <div className="relative">
                <CheckCircle className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="password"
                  value={formData.confirmPassword}
                  onChange={(e) => setFormData({ ...formData, confirmPassword: e.target.value })}
                  placeholder="Repite tu contraseña"
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all"
                />
              </div>
            </div>

            {/* Account Type */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Tipo de cuenta
              </label>
              <div className="grid grid-cols-2 gap-4">
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, role: 'Usuario' })}
                  className={`p-4 border-2 rounded-2xl font-semibold transition-all ${
                    formData.role === 'Usuario'
                      ? 'bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] text-white border-[#4CAF50] shadow-lg'
                      : 'bg-white text-gray-700 border-gray-200 hover:border-[#4CAF50]'
                  }`}
                >
                  Usuario
                </button>
                <button
                  type="button"
                  onClick={() => setFormData({ ...formData, role: 'Administrador' })}
                  className={`p-4 border-2 rounded-2xl font-semibold transition-all ${
                    formData.role === 'Administrador'
                      ? 'bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] text-white border-[#4CAF50] shadow-lg'
                      : 'bg-white text-gray-700 border-gray-200 hover:border-[#4CAF50]'
                  }`}
                >
                  Administrador
                </button>
              </div>
            </div>

            {/* Error Message */}
            {error && (
              <div className="p-4 bg-red-50 border-2 border-red-200 rounded-2xl">
                <p className="text-sm text-red-600 text-center font-medium">{error}</p>
              </div>
            )}

            {/* Submit Button */}
            <button
              type="submit"
              className="w-full px-8 py-4 bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] text-white rounded-2xl font-semibold text-lg hover:shadow-2xl hover:shadow-[#4CAF50]/30 hover:scale-105 transition-all"
            >
              Crear cuenta
            </button>

            {/* Divider */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-gray-200"></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-4 bg-white text-gray-500">o</span>
              </div>
            </div>

            {/* Login Link */}
            <div className="text-center">
              <p className="text-gray-600">
                ¿Ya tienes una cuenta?{' '}
                <Link to="/login" className="text-[#2E7D32] font-semibold hover:text-[#4CAF50] transition-colors">
                  Inicia sesión aquí
                </Link>
              </p>
            </div>

            {/* Back to Home */}
            <div className="text-center pt-4">
              <Link to="/" className="text-sm text-gray-500 hover:text-[#2E7D32] transition-colors">
                ← Volver al inicio
              </Link>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}

// frontend/src/app/features/auth/register/register.component.ts
import { Component } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { LucideAngularModule, Leaf, Mail, Lock, User } from 'lucide-angular';
import { AUTH_STRINGS } from '../strings';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    RouterModule
  ],
  providers: [
    { provide: LucideAngularModule, useValue: LucideAngularModule.pick({ Leaf, Mail, Lock, User }) }
  ],
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {

  registerForm: FormGroup;
  error = '';

  strings = AUTH_STRINGS;

  constructor(private fb: FormBuilder, private router: Router, private authService: AuthService) {
    this.registerForm = this.fb.group({
      fullName: ['', Validators.required],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      confirmPassword: ['', Validators.required],
      role: ['Usuario']
    }, {
      validators: this.passwordsMatch
    });
  }

  passwordsMatch(group: FormGroup) {
    const pass = group.get('password')?.value;
    const confirm = group.get('confirmPassword')?.value;
    return pass === confirm ? null : { mismatch: true };
  }

  onSubmit() {
    if (this.registerForm.invalid) {
      if (this.registerForm.hasError('mismatch')) {
        this.error = this.strings.errorPasswordMismatch;
      } else {
        this.error = this.strings.errorRequired;
      }
      return;
    }

    const { fullName, email, password } = this.registerForm.value;

    this.authService.register({ nombre: fullName, email, password }).subscribe({
      next: (response) => {
        console.log('Registro exitoso', response);
        this.router.navigate(['/']);
      },
      error: (err) => {
        console.error('Error en el registro', err);
        this.error = err.error?.message || 'Error al registrar. Por favor, inténtelo de nuevo.';
      }
    });
  }

}

<div class="min-h-screen bg-gradient-to-br from-[#E8F5E9] to-[#C8E6C9] flex items-center justify-center p-6">
  <div class="w-full max-w-md">

    <a routerLink="/" class="flex items-center justify-center gap-3 group w-full mb-8">
      <div class="w-12 h-12 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-2xl flex items-center justify-center shadow-lg group-hover:shadow-xl transition-shadow">
        <lucide-icon name="leaf" class="w-7 h-7 text-white"></lucide-icon>
      </div>
      <span class="text-2xl font-bold bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] bg-clip-text text-transparent">
        EcoLand 
      </span>
    </a>

    <div class="bg-white rounded-3xl shadow-2xl p-8 border-2 border-gray-100">

      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">
          {{ 'auth.register.title' | translate }}
        </h1>
        <p class="text-gray-600">
          {{ 'auth.register.subtitle' | translate }}
        </p>
      </div>

      <form [formGroup]="registerForm" (ngSubmit)="onSubmit()" class="space-y-6">

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.register.inputs.full_name.label' | translate }}
          </label>
          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <circle cx="12" cy="7" r="4" stroke-width="2"/>
              <path stroke-width="2" d="M5.5 21a8.38 8.38 0 0113 0"/>
            </svg>
            <input
              type="text"
              formControlName="fullName"
              [placeholder]="'auth.register.inputs.full_name.placeholder' | translate"
              class="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50]"
            >
          </div>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.login.inputs.email.label' | translate }}
          </label>
          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-width="2" d="M4 4h16v16H4z"/><path stroke-width="2" d="M22 6l-10 7L2 6"/>
            </svg>
            <input
              type="email"
              formControlName="email"
              [placeholder]="'auth.login.inputs.email.placeholder' | translate"
              class="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50]"
            >
          </div>
          <div *ngIf="registerForm.get('email')?.invalid && (registerForm.get('email')?.dirty || registerForm.get('email')?.touched)" 
               class="mt-2 p-3 bg-red-100 border-l-4 border-red-600 text-red-700 text-sm font-bold shadow-sm flex flex-col gap-1">
            <span *ngIf="registerForm.get('email')?.errors?.['required']">⚠️ {{ 'auth.validation.required_email' | translate }}</span>
            <ng-container *ngIf="!registerForm.get('email')?.errors?.['required']">
              <span *ngIf="!emailRules.hasAt">⚠️ {{ 'auth.validation.missing_at' | translate }}</span>
              <span *ngIf="!emailRules.hasCom">⚠️ {{ 'auth.validation.missing_com' | translate }}</span>
            </ng-container>
          </div>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.login.inputs.password.label' | translate }}
          </label>
          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <rect x="5" y="11" width="14" height="10" rx="2" stroke-width="2"/>
              <path stroke-width="2" d="M8 11V7a4 4 0 018 0v4"/>
            </svg>
            <input
              type="password"
              formControlName="password"
              [placeholder]="'auth.login.inputs.password.placeholder' | translate"
              class="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50]"
            >
          </div>
          <div *ngIf="registerForm.get('password')?.invalid && (registerForm.get('password')?.dirty || registerForm.get('password')?.touched)" 
               class="mt-2 p-3 bg-red-100 border-l-4 border-red-600 text-red-700 text-sm font-bold shadow-sm flex flex-col gap-1">
            <span *ngIf="registerForm.get('password')?.errors?.['required']">⚠️ {{ 'auth.validation.required_password' | translate }}</span>
            <ng-container *ngIf="!registerForm.get('password')?.errors?.['required']">
              <span *ngIf="!passwordRules.minLength">⚠️ {{ 'auth.validation.password_rules.min_length' | translate }}</span>
              <span *ngIf="!passwordRules.hasUpper">⚠️ {{ 'auth.validation.password_rules.upper' | translate }}</span>
              <span *ngIf="!passwordRules.hasLower">⚠️ {{ 'auth.validation.password_rules.lower' | translate }}</span>
              <span *ngIf="!passwordRules.hasNumber">⚠️ {{ 'auth.validation.password_rules.number' | translate }}</span>
              <span *ngIf="!passwordRules.hasSpecial">⚠️ {{ 'auth.validation.password_rules.special' | translate }}</span>
            </ng-container>
          </div>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.register.inputs.confirm_password.label' | translate }}
          </label>
          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <rect x="5" y="11" width="14" height="10" rx="2" stroke-width="2"/>
              <path stroke-width="2" d="M8 11V7a4 4 0 018 0v4"/>
            </svg>
            <input
              type="password"
              formControlName="confirmPassword"
              [placeholder]="'auth.register.inputs.confirm_password.placeholder' | translate"
              class="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50]"
            >
          </div>
          <div *ngIf="registerForm.hasError('mismatch') && (registerForm.get('confirmPassword')?.dirty || registerForm.get('confirmPassword')?.touched)" 
               class="mt-2 p-3 bg-red-100 border-l-4 border-red-600 text-red-700 text-sm font-bold shadow-sm flex flex-col gap-1">
            <span>⚠️ {{ 'auth.validation.password_mismatch' | translate }}</span>
          </div>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.login.inputs.role.label' | translate }}
          </label>
          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <circle cx="12" cy="7" r="4" stroke-width="2"/>
              <path stroke-width="2" d="M5.5 21a8.38 8.38 0 0113 0"/>
            </svg>
            <select formControlName="role" class="w-full pl-12 pr-10 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl appearance-none">
              <option value="Usuario">{{ 'auth.login.inputs.role.user' | translate }}</option>
              <option value="Administrador">{{ 'auth.login.inputs.role.admin' | translate }}</option>
            </select>
            <svg xmlns="http://www.w3.org/2000/svg" class="absolute right-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-width="2" d="M6 9l6 6 6-6"/>
            </svg>
          </div>
        </div>

        <div *ngIf="error" class="p-4 bg-red-50 border-2 border-red-200 rounded-2xl">
          <p class="text-sm text-red-600 text-center font-medium">{{ error }}</p>
        </div>

        <button
          type="submit"
          [disabled]="isLoading"
          class="w-full px-8 py-4 bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] text-white rounded-2xl font-semibold text-lg 
          hover:shadow-2xl hover:shadow-[#4CAF50]/30 hover:scale-105 transition-all duration-300 disabled:opacity-75 disabled:cursor-wait"
          >
          <span *ngIf="!isLoading">{{ 'auth.register.submit_button' | translate }}</span>
          <span *ngIf="isLoading">{{ 'shared.loading_generic' | translate }}</span>
        </button>

        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-200"></div>
          </div>
          <div class="relative flex justify-center text-sm">
            <span class="px-4 bg-white text-gray-500">{{ 'shared.or_separator' | translate }}</span>
          </div>
        </div>

        <div class="flex justify-center my-4">
          <asl-google-signin-button type="standard" size="large"></asl-google-signin-button>
        </div>

        <div class="text-center">
          <p class="text-gray-600">
            {{ 'auth.register.footer.login_question' | translate }}
            <a routerLink="/login" class="text-[#2E7D32] font-semibold hover:text-[#4CAF50] cursor-pointer">
              {{ 'auth.register.footer.login_link' | translate }}
            </a>
          </p>
        </div>

        <div class="text-center pt-4">
          <a routerLink="/" class="text-sm text-gray-500 hover:text-[#2E7D32] cursor-pointer">
            {{ 'auth.login.footer.back_home' | translate }}
          </a>
        </div>
      </form>
    </div>
  </div>
</div>
