// src/components/Footer.tsx
import { Leaf, Mail, Phone, MapPin } from 'lucide-react';
import { Link } from 'react-router';

export function Footer() {
  return (
    <footer className="bg-gradient-to-br from-[#2E7D32] to-[#1B5E20] text-white mt-20">
      <div className="max-w-7xl mx-auto px-6 lg:px-8 py-16">
        <div className="grid md:grid-cols-4 gap-12 mb-12">
          {/* Logo & Description */}
          <div className="md:col-span-2">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-12 h-12 bg-white rounded-2xl flex items-center justify-center">
                <Leaf className="w-7 h-7 text-[#2E7D32]" />
              </div>
              <span className="text-2xl font-bold">EcoLand</span>
            </div>
            <p className="text-[#A5D6A7] leading-relaxed mb-6">
              Plataforma líder en gestión ambiental de Cochabamba. Juntos construimos un futuro más verde y sostenible.
            </p>
            <div className="space-y-3">
              <div className="flex items-center gap-3 text-[#A5D6A7]">
                <MapPin className="w-4 h-4" />
                <span className="text-sm">Cochabamba, Bolivia</span>
              </div>
              <div className="flex items-center gap-3 text-[#A5D6A7]">
                <Mail className="w-4 h-4" />
                <span className="text-sm">contacto@ecoland.bo</span>
              </div>
              <div className="flex items-center gap-3 text-[#A5D6A7]">
                <Phone className="w-4 h-4" />
                <span className="text-sm">+591 4 XXX XXXX</span>
              </div>
            </div>
          </div>

          {/* Links */}
          <div>
            <h3 className="font-semibold text-lg mb-4">Plataforma</h3>
            <ul className="space-y-3">
              <li>
                <Link to="/reforestacion" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Reforestación
                </Link>
              </li>
              <li>
                <Link to="/reciclaje" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Reciclaje
                </Link>
              </li>
              <li>
                <Link to="/estadisticas" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Estadísticas
                </Link>
              </li>
              <li>
                <Link to="/admin" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Panel Admin
                </Link>
              </li>
            </ul>
          </div>

          {/* Support */}
          <div>
            <h3 className="font-semibold text-lg mb-4">Ayuda</h3>
            <ul className="space-y-3">
              <li>
                <a href="#" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Preguntas frecuentes
                </a>
              </li>
              <li>
                <a href="#" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Guía de usuario
                </a>
              </li>
              <li>
                <a href="#" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Contacto
                </a>
              </li>
              <li>
                <a href="#" className="text-[#A5D6A7] hover:text-white transition-colors text-sm">
                  Términos y condiciones
                </a>
              </li>
            </ul>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t border-white/20 text-center">
          <p className="text-[#A5D6A7] text-sm">
            © 2026 EcoLand. Todos los derechos reservados. Haciendo de Cochabamba una ciudad más verde 🌱
          </p>
        </div>
      </div>
    </footer>
  );
}

// frontend/src/app/shared/components/footer/footer.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FeatureFlagService } from '../../../core/services/feature-flag.service';
import { AuthService } from '../../../core/services/auth.service';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-footer',
  standalone: false,
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent implements OnInit, OnDestroy {
  private subscription!: Subscription;

  constructor(
    private featureFlagService: FeatureFlagService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.subscription = this.featureFlagService.features$.subscribe(() => {
      // Reactively update when toggles change
    });
  }

  ngOnDestroy(): void {
    if (this.subscription) {
      this.subscription.unsubscribe();
    }
  }

  isFeatureEnabled(featureName: string): boolean {
    return this.featureFlagService.isFeatureEnabled(featureName);
  }

  get isAdmin(): boolean {
    const user = this.authService.getUser();
    return user && this.authService.normalizeRole(user.role) === 'admin';
  }
}

<footer class="bg-gradient-to-br from-[#2E7D32] to-[#1B5E20] text-white mt-20"> 
  <div class="max-w-7xl mx-auto px-6 lg:px-8 py-16">
    <div class="grid md:grid-cols-4 gap-12 mb-12">
      <div class="md:col-span-2">
        <div class="flex items-center gap-3 mb-4">
          <div class="w-12 h-12 bg-white rounded-2xl flex items-center justify-center">
            <lucide-icon name="leaf" class="w-7 h-7 text-[#2E7D32]"></lucide-icon>
          </div>
          <span class="text-2xl font-bold">EcoLand</span>
        </div>
        <p class="text-[#A5D6A7] leading-relaxed mb-6">
          {{ 'footer.description' | translate }}
        </p>
        <div class="space-y-3">
          <div class="flex items-center gap-3 text-[#A5D6A7]">
            <lucide-icon name="map-pin" class="w-4 h-4"></lucide-icon>
            <span class="text-sm">Cochabamba, Bolivia</span>
          </div>
          <div class="flex items-center gap-3 text-[#A5D6A7]">
            <lucide-icon name="mail" class="w-4 h-4"></lucide-icon>
            <span class="text-sm">contacto&#64;ecoland.bo</span>
          </div>
          <div class="flex items-center gap-3 text-[#A5D6A7]">
            <lucide-icon name="phone" class="w-4 h-4"></lucide-icon>
            <span class="text-sm">+591 4 XXX XXXX</span>
          </div>
        </div>
      </div>

      <div>
        <h3 class="font-semibold text-lg mb-4">{{ 'footer.columns.platform.title' | translate }}</h3>
        <ul class="space-y-3">
          <li *ngIf="isFeatureEnabled('reforestacion')">
            <a routerLink="/reforestacion" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.platform.reforestation' | translate }}
            </a>
          </li>
          <li *ngIf="isFeatureEnabled('reciclaje')">
            <a routerLink="/reciclaje" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.platform.recycling' | translate }}
            </a>
          </li>
          <li *ngIf="isFeatureEnabled('estadisticas')">
            <a routerLink="/estadisticas" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.platform.stats' | translate }}
            </a>
          </li>
          <li *ngIf="isAdmin">
            <a routerLink="/admin" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.platform.admin' | translate }}
            </a>
          </li>
        </ul>
      </div>

      <div>
        <h3 class="font-semibold text-lg mb-4">{{ 'footer.columns.support.title' | translate }}</h3>
        <ul class="space-y-3">
          <li>
            <a href="#" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.support.faq' | translate }}
            </a>
          </li>
          <li>
            <a href="#" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.support.guide' | translate }}
            </a>
          </li>
          <li>
            <a href="#" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.support.contact' | translate }}
            </a>
          </li>
          <li>
            <a href="#" class="text-[#A5D6A7] hover:text-white transition-colors text-sm">
              {{ 'footer.columns.support.terms' | translate }}
            </a>
          </li>
        </ul>
      </div>
    </div>

    <div class="pt-8 border-t border-white/20 text-center">
      <p class="text-[#A5D6A7] text-sm">
        {{ 'footer.bottom' | translate }}
      </p>
    </div>
  </div>
</footer>
