// frontend/src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { LucideAngularModule, Leaf, Mail, Lock, User } from 'lucide-angular';
import { AUTH_STRINGS } from '../strings';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    RouterModule
  ],
  providers: [
    { provide: LucideAngularModule, useValue: LucideAngularModule.pick({ Leaf, Mail, Lock, User }) }
  ],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  loginForm: FormGroup;
  error = '';

  strings = AUTH_STRINGS;

  get emailRules() {
    const val = this.loginForm?.get('email')?.value || '';
    return {
      hasAt: val.includes('@'),
      hasCom: val.endsWith('.com')
    };
  }

  constructor(private fb: FormBuilder, private router: Router, private authService: AuthService) {

    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email, Validators.pattern(/^[^\s@]+@[^\s@]+\.com$/i)]],
      password: ['', Validators.required],
      role: ['Usuario']
    });

  }

  onSubmit() {

    if (this.loginForm.invalid) {
      this.error = this.strings.errorRequired;
      return;
    }

    const { email, password, role } = this.loginForm.value;

    this.authService.login({ email, password }).subscribe({
      next: (response: any) => {
        this.authService.setSession(response);

        const selectedRole = role === 'Administrador' ? 'admin' : 'usuario';
        const actualRole = this.authService.normalizeRole(response?.role);

        if (selectedRole !== actualRole) {
          this.authService.logout();
          this.error = selectedRole === 'admin'
            ? 'Tu cuenta no tiene permisos de administrador.'
            : 'Tu cuenta es de administrador. Elige el acceso de administrador.';
          return;
        }
        
        if (actualRole === 'admin') {
          this.router.navigate(['/admin']);
        } else {
          this.router.navigate(['/']);
        }
      },
      error: (err: any) => {
        console.error('Error al iniciar sesión', err);
        this.error = 'Contraseña o Correo incorrectos intente de nuevo';
      }
    });

  }

}
<div class="min-h-screen bg-gradient-to-br from-[#E8F5E9] to-[#C8E6C9] flex items-center justify-center p-6">
  <div class="w-full max-w-md">

    <a routerLink="/" class="flex items-center justify-center gap-3 group w-full mb-8">
      <div class="w-12 h-12 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-2xl flex items-center justify-center shadow-lg group-hover:shadow-xl transition-shadow">
        <lucide-icon name="leaf" class="w-7 h-7 text-white"></lucide-icon>
      </div>
      <span class="text-2xl font-bold bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] bg-clip-text text-transparent">
        EcoLand
      </span>
    </a>

    <div class="bg-white rounded-3xl shadow-2xl p-8 border-2 border-gray-100">

      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-gray-900 mb-2">
          {{ 'auth.login.title' | translate }}
        </h1>
        <p class="text-gray-600">
          {{ 'auth.login.subtitle' | translate }}
        </p>
      </div>

      <div *ngIf="infoMessage" class="p-4 bg-[#E8F5E9] border-2 border-[#C8E6C9] rounded-2xl mb-6">
        <p class="text-sm text-[#2E7D32] text-center font-medium">
          {{ infoMessage }}
        </p>
      </div>

      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-6">

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.login.inputs.email.label' | translate }}
          </label>

          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"
                 fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-width="2" d="M4 4h16v16H4z"/>
              <path stroke-width="2" d="M22 6l-10 7L2 6"/>
            </svg>

            <input
              type="email"
              formControlName="email"
              [placeholder]="'auth.login.inputs.email.placeholder' | translate"
              class="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50]"
            >
          </div>
          
          <div *ngIf="loginForm.get('email')?.invalid && (loginForm.get('email')?.dirty || loginForm.get('email')?.touched)" 
               class="mt-2 p-3 bg-red-100 border-l-4 border-red-600 text-red-700 text-sm font-bold shadow-sm flex flex-col gap-1 text-left">
            
            <span *ngIf="loginForm.get('email')?.errors?.['required']">
              ⚠️ {{ 'auth.validation.required' | translate }}
            </span>
            
            <ng-container *ngIf="!loginForm.get('email')?.errors?.['required']">
              <span *ngIf="!emailRules.hasAt">
                ⚠️ {{ 'auth.validation.missing_at' | translate }}
              </span>
              <span *ngIf="!emailRules.hasCom">
                ⚠️ {{ 'auth.validation.missing_com' | translate }}
              </span>
            </ng-container>
          </div>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.login.inputs.password.label' | translate }}
          </label>

          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg"
                 class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"
                 fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <rect x="5" y="11" width="14" height="10" rx="2" stroke-width="2"/>
              <path stroke-width="2" d="M8 11V7a4 4 0 018 0v4"/>
            </svg>

            <input
              type="password"
              formControlName="password"
              [placeholder]="'auth.login.inputs.password.placeholder' | translate"
              class="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50]"
            >
          </div>
        </div>

        <div>
          <label class="block text-sm font-semibold text-gray-700 mb-2">
            {{ 'auth.login.inputs.role.label' | translate }}
          </label>

          <div class="relative">
            <svg xmlns="http://www.w3.org/2000/svg"
                class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"
                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <circle cx="12" cy="7" r="4" stroke-width="2"/>
                <path stroke-width="2" d="M5.5 21a8.38 8.38 0 0113 0"/>
            </svg>

            <select
                formControlName="role"
                class="w-full pl-12 pr-10 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl appearance-none"
            >
                <option value="Usuario">{{ 'auth.login.inputs.role.user' | translate }}</option>
                <option value="Administrador">{{ 'auth.login.inputs.role.admin' | translate }}</option>
            </select>

            <svg xmlns="http://www.w3.org/2000/svg"
                class="absolute right-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none"
                fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-width="2" d="M6 9l6 6 6-6"/>
            </svg>
          </div>
        </div>

        <div *ngIf="error" class="p-4 bg-red-50 border-2 border-red-200 rounded-2xl">
          <p class="text-sm text-red-600 text-center font-medium">
            {{ error }}
          </p>
        </div>

        <button
          type="submit"
          [disabled]="isLoading"
          class="w-full px-8 py-4 bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] text-white rounded-2xl font-semibold text-lg 
          hover:shadow-2xl hover:shadow-[#4CAF50]/30 hover:scale-105 transition-all duration-300 disabled:opacity-75 disabled:cursor-wait"
          >
          <span *ngIf="!isLoading">{{ 'auth.login.submit_button' | translate }}</span>
          <span *ngIf="isLoading">{{ 'auth.login.loading' | translate }}</span>
        </button>

        <div class="relative">
          <div class="absolute inset-0 flex items-center">
            <div class="w-full border-t border-gray-200"></div>
          </div>

          <div class="relative flex justify-center text-sm">
            <span class="px-4 bg-white text-gray-500">
              {{ 'shared.or_separator' | translate }}
            </span>
          </div>
        </div>

        <div class="flex justify-center my-4">
          <asl-google-signin-button type="standard" size="large"></asl-google-signin-button>
        </div>

        <div class="text-center">
          <p class="text-gray-600">
            {{ 'auth.login.footer.register_question' | translate }}
            <a routerLink="/register" 
            class="text-[#2E7D32] font-semibold hover:text-[#4CAF50] cursor-pointer">
              {{ 'auth.login.footer.register_link' | translate }}
            </a>
          </p>
        </div>

        <div class="text-center pt-4">
          <a routerLink="/" 
          class="text-sm text-gray-500 hover:text-[#2E7D32] cursor-pointer">
            {{ 'auth.login.footer.back_home' | translate }}
          </a>
        </div>

      </form>

    </div>
  </div>
</div>

// src/pages/Login.tsx
import { useState } from 'react';
import { Leaf, Mail, Lock, User } from 'lucide-react';
import { Link, useNavigate } from 'react-router';
import { useAuth } from '../contexts/AuthContext';

export default function Login() {
  const navigate = useNavigate();
  const { login } = useAuth();
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    role: 'Usuario' as 'Usuario' | 'Administrador',
  });
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!formData.email || !formData.password) {
      setError('Por favor complete todos los campos');
      return;
    }

    const success = login(formData.email, formData.password, formData.role);
    if (success) {
      if (formData.role === 'Administrador') {
        navigate('/admin');
      } else {
        navigate('/');
      }
    } else {
      setError('Error al iniciar sesión');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#E8F5E9] to-[#C8E6C9] flex items-center justify-center p-6">
      <div className="w-full max-w-md">
        {/* Logo */}
        <Link to="/" className="flex items-center justify-center gap-3 mb-8">
          <div className="w-16 h-16 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-3xl flex items-center justify-center shadow-2xl">
            <Leaf className="w-9 h-9 text-white" />
          </div>
          <span className="text-4xl font-bold bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] bg-clip-text text-transparent">
            EcoLand
          </span>
        </Link>

        {/* Login Card */}
        <div className="bg-white rounded-3xl shadow-2xl p-8 border-2 border-gray-100">
          <div className="text-center mb-8">
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Iniciar sesión</h1>
            <p className="text-gray-600">Bienvenido de nuevo a EcoLand</p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Email */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Correo electrónico
              </label>
              <div className="relative">
                <Mail className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="tu@email.com"
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all"
                />
              </div>
            </div>

            {/* Password */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Contraseña
              </label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <input
                  type="password"
                  value={formData.password}
                  onChange={(e) => setFormData({ ...formData, password: e.target.value })}
                  placeholder="••••••••"
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all"
                />
              </div>
            </div>

            {/* User Type */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">
                Tipo de usuario
              </label>
              <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" />
                <select
                  value={formData.role}
                  onChange={(e) => setFormData({ ...formData, role: e.target.value as 'Usuario' | 'Administrador' })}
                  className="w-full pl-12 pr-4 py-4 bg-gray-50 border-2 border-gray-200 rounded-2xl focus:outline-none focus:border-[#4CAF50] focus:bg-white transition-all appearance-none cursor-pointer"
                >
                  <option value="Usuario">Usuario</option>
                  <option value="Administrador">Administrador</option>
                </select>
              </div>
            </div>

            {/* Error Message */}
            {error && (
              <div className="p-4 bg-red-50 border-2 border-red-200 rounded-2xl">
                <p className="text-sm text-red-600 text-center font-medium">{error}</p>
              </div>
            )}

            {/* Submit Button */}
            <button
              type="submit"
              className="w-full px-8 py-4 bg-gradient-to-r from-[#2E7D32] to-[#4CAF50] text-white rounded-2xl font-semibold text-lg hover:shadow-2xl hover:shadow-[#4CAF50]/30 hover:scale-105 transition-all"
            >
              Iniciar sesión
            </button>

            {/* Divider */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <div className="w-full border-t border-gray-200"></div>
              </div>
              <div className="relative flex justify-center text-sm">
                <span className="px-4 bg-white text-gray-500">o</span>
              </div>
            </div>

            {/* Register Link */}
            <div className="text-center">
              <p className="text-gray-600">
                ¿No tienes una cuenta?{' '}
                <Link to="/register" className="text-[#2E7D32] font-semibold hover:text-[#4CAF50] transition-colors">
                  Regístrate aquí
                </Link>
              </p>
            </div>

            {/* Back to Home */}
            <div className="text-center pt-4">
              <Link to="/" className="text-sm text-gray-500 hover:text-[#2E7D32] transition-colors">
                ← Volver al inicio
              </Link>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
