// frontend/src/app/features/statistics/statistics.component.ts
import { Component, OnInit } from '@angular/core';
import { StatisticsService, ComprehensiveStatistics } from '../../core/services/statistics.service';
import { ChartConfiguration, ChartData, ChartType, registerables } from 'chart.js';
import { Chart } from 'chart.js';
import { catchError, finalize, forkJoin, of, timeout } from 'rxjs';

Chart.register(...registerables);

@Component({
  selector: 'app-statistics',
  templateUrl: './statistics.component.html',
  styleUrl: './statistics.component.css',
  standalone: false
})
export class StatisticsComponent implements OnInit {
  isLoading = true;
  data: ComprehensiveStatistics | null = null;

  // Summary Cards
  summaryCards = [
    { icon: 'tree-deciduous', label: 'Árboles Plantados', value: '0', subtitle: 'equivalente a 185 hectáreas de bosque' },
    { icon: 'leaf', label: 'CO2 Mitigado', value: '0', subtitle: 'kg/año reducidos' },
    { icon: 'recycle', label: 'Campañas Completadas', value: '0', subtitle: '' },
    { icon: 'droplets', label: 'Agua Ahorrada', value: '0', subtitle: 'litros' },
  ];

  impactCards = [
    { icon: 'tree-deciduous', label: 'Árboles plantados', value: '15,432', detail: 'Equivalente a 185 hectáreas de bosque' },
    { icon: 'recycle', label: 'Residuos reciclados', value: '328 ton', detail: 'Reducción de 520 toneladas de CO₂' },
    { icon: 'droplets', label: 'Agua ahorrada', value: '2.4M L', detail: 'Gracias al reciclaje de papel y plástico' },
  ];

  // Bar chart: Monthly planted trees
  public monthlyChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: 'white',
        titleColor: '#111827',
        bodyColor: '#4b5563',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        padding: 12,
        cornerRadius: 16,
        displayColors: false
      }
    },
    scales: {
      x: { grid: { display: false } },
      y: { grid: { color: '#f3f4f6' } }
    }
  };
  public monthlyChartType: ChartType = 'bar';
  public monthlyChartData: ChartData<'bar'> = {
    labels: [],
    datasets: [
      {
        data: [],
        backgroundColor: '#22c55e',
        borderColor: '#16a34a',
        borderWidth: 1,
        borderRadius: 12,
        label: 'Árboles Plantados'
      }
    ]
  };

  // Pie chart: Residue distribution
  public residueChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        position: 'right',
        labels: { padding: 20, font: { size: 12 } }
      },
      tooltip: {
        backgroundColor: 'white',
        titleColor: '#111827',
        bodyColor: '#4b5563',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        padding: 12,
        cornerRadius: 16,
        displayColors: true,
        callbacks: {
          label: (context) => `${context.label}: ${context.parsed}%`
        }
      }
    }
  };
  public residueChartType: ChartType = 'doughnut';
  public residueChartData: ChartData<'doughnut'> = {
    labels: [],
    datasets: [
      {
        data: [],
        backgroundColor: ['#22c55e', '#84cc16', '#06b6d4', '#8b5cf6', '#ec4899'],
        borderColor: '#ffffff',
        borderWidth: 2
      }
    ]
  };

  // Bar chart: Zone activity
  public zoneChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: 'white',
        titleColor: '#111827',
        bodyColor: '#4b5563',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        padding: 12,
        cornerRadius: 16,
        displayColors: false
      }
    },
    scales: {
      x: { grid: { display: false } },
      y: { grid: { color: '#f3f4f6' } }
    }
  };
  public zoneChartType: ChartType = 'bar';
  public zoneChartData: ChartData<'bar'> = {
    labels: [],
    datasets: [
      {
        data: [],
        backgroundColor: '#8b5cf6',
        borderColor: '#7c3aed',
        borderWidth: 1,
        borderRadius: 12,
        label: 'Actividades por Zona'
      }
    ]
  };

  // Line chart: Volunteer growth
  public volunteerChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: 'white',
        titleColor: '#111827',
        bodyColor: '#4b5563',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        padding: 12,
        cornerRadius: 16,
        displayColors: false
      }
    },
    scales: {
      x: { grid: { display: false } },
      y: { grid: { color: '#f3f4f6' } }
    }
  };
  public volunteerChartType: ChartType = 'line';
  public volunteerChartData: ChartData<'line'> = {
    labels: [],
    datasets: [
      {
        data: [],
        borderColor: '#f97316',
        backgroundColor: 'rgba(249, 115, 22, 0.1)',
        borderWidth: 2,
        fill: true,
        pointBackgroundColor: '#f97316',
        pointBorderColor: '#ffffff',
        pointBorderWidth: 2,
        pointRadius: 6,
        tension: 0.4,
        label: 'Crecimiento de Voluntarios'
      }
    ]
  };

  // Bar chart: Campaign vs Participants
  public campaignChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: { display: false },
      tooltip: {
        backgroundColor: 'white',
        titleColor: '#111827',
        bodyColor: '#4b5563',
        borderColor: '#e5e7eb',
        borderWidth: 1,
        padding: 12,
        cornerRadius: 16,
        displayColors: false
      }
    },
    scales: {
      x: { grid: { display: false } },
      y: { grid: { color: '#f3f4f6' } }
    }
  };
  public campaignChartType: ChartType = 'bar';
  public campaignChartData: ChartData<'bar'> = {
    labels: [],
    datasets: [
      {
        data: [],
        backgroundColor: '#4CAF50',
        borderColor: '#2E7D32',
        borderWidth: 1,
        borderRadius: 12,
        label: 'Participantes por Campaña'
      }
    ]
  };

  constructor(private statsService: StatisticsService) {}

  ngOnInit(): void {
    const comprehensive$ = this.statsService.getComprehensiveStatistics().pipe(
      timeout(5000),
      catchError(() => of(this.getDefaultComprehensiveData()))
    );

    const campaigns$ = this.statsService.getCampaignParticipants().pipe(
      timeout(5000),
      catchError(() => of([]))
    );

    forkJoin({
      comprehensive: comprehensive$,
      campaigns: campaigns$
    }).pipe(
      finalize(() => {
        this.isLoading = false;
      })
    ).subscribe(({ comprehensive, campaigns }) => {
      this.data = comprehensive;
      this.populateSummaryCards(comprehensive);
      this.populateCharts(comprehensive, campaigns);
    });
  }

  private populateSummaryCards(data: ComprehensiveStatistics): void {
    this.summaryCards[0].value = data.plantedTrees.toLocaleString();
    this.summaryCards[0].subtitle = `${(data.plantedTrees / 1000).toFixed(0)} hectáreas de bosque`;
    
    this.summaryCards[1].value = data.mitigatedCo2Kg.toLocaleString(undefined, { maximumFractionDigits: 0 });
    this.summaryCards[1].subtitle = 'kg/año reducidos';
    
    this.summaryCards[2].value = data.completedCampaigns.toLocaleString();
    
    this.summaryCards[3].value = (data.waterSavedLiters / 1000000).toFixed(1) + 'M';
    this.summaryCards[3].subtitle = 'litros ahorrados';

    // Update impact cards
    this.impactCards[0].value = data.plantedTrees.toLocaleString();
    this.impactCards[0].detail = `Equivalente a ${(data.forestAreaHectares).toFixed(0)} hectáreas de bosque`;
    
    this.impactCards[1].value = '328 ton';
    this.impactCards[1].detail = `Reducción de ${(data.mitigatedCo2Kg / 1000).toFixed(0)} toneladas de CO₂`;
    
    this.impactCards[2].value = (data.waterSavedLiters / 1000000).toFixed(1) + 'M L';
  }

  private populateCharts(data: ComprehensiveStatistics, campaigns: any[]): void {
    // Monthly planted trees
    this.monthlyChartData.labels = data.monthlyPlantedTrees.map(m => m.month);
    this.monthlyChartData.datasets[0].data = data.monthlyPlantedTrees.map(m => m.value);

    // Residue distribution
    this.residueChartData.labels = data.residueDistribution.map(r => r.type);
    this.residueChartData.datasets[0].data = data.residueDistribution.map(r => r.percentage);

    // Zone activity
    this.zoneChartData.labels = data.zoneActivity.map(z => z.zone);
    this.zoneChartData.datasets[0].data = data.zoneActivity.map(z => z.activities);

    // Volunteer growth
    this.volunteerChartData.labels = data.volunteerGrowth.map(v => v.month);
    this.volunteerChartData.datasets[0].data = data.volunteerGrowth.map(v => v.totalVolunteers);

    // Campaign vs Participants
    this.campaignChartData.labels = campaigns.map(c => c.title);
    this.campaignChartData.datasets[0].data = campaigns.map(c => c.participants);
  }

  private getDefaultComprehensiveData(): ComprehensiveStatistics {
    return {
      totalCampaigns: 0,
      activeCampaigns: 0,
      totalParticipants: 0,
      completedCampaigns: 0,
      plantedTrees: 0,
      mitigatedCo2Kg: 0,
      monthlyPlantedTrees: [],
      residueDistribution: [],
      zoneActivity: [],
      volunteerGrowth: [],
      waterSavedLiters: 0,
      forestAreaHectares: 0
    };
  }
}

<main class="min-h-screen bg-white">
  <!-- Hero Section -->
  <section class="relative bg-gradient-to-br from-[#2E7D32] to-[#1B5E20] text-white py-20">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="max-w-3xl">
        <div class="inline-block px-4 py-2 bg-white/20 backdrop-blur-sm rounded-full text-sm font-medium mb-6">
          {{ 'stats.hero.badge' | translate }}
        </div>
        <h1 class="text-5xl font-bold mb-6">
          {{ 'stats.hero.title' | translate }}
        </h1>
        <p class="text-xl text-[#A5D6A7] mb-8">
          {{ 'stats.hero.description' | translate }}
        </p>
      </div>
    </div>
  </section>

  <!-- Summary Cards Section -->
  <section class="py-16 bg-[#E8F5E9]" *ngIf="!isLoading; else loadingState">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
        <div *ngFor="let stat of summaryCards" class="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all hover:-translate-y-1">
          <div class="w-16 h-16 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-2xl flex items-center justify-center mb-6 shadow-lg">
            <lucide-icon [name]="stat.icon" class="w-8 h-8 text-white"></lucide-icon>
          </div>
          <p class="text-4xl font-bold text-gray-900 mb-2">{{ stat.value }}</p>
          <p class="text-gray-600 font-medium">{{ stat.label }}</p>
          <p class="text-sm text-gray-500 mt-2">{{ stat.subtitle }}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Monthly Trees & Residue Distribution -->
  <section class="py-16 bg-gray-50" *ngIf="!isLoading">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="grid lg:grid-cols-2 gap-8">
        <!-- Monthly Planted Trees -->
        <div class="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
          <div class="flex items-center gap-4 mb-6">
            <div class="w-12 h-12 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-2xl flex items-center justify-center">
              <lucide-icon name="leaf" class="w-6 h-6 text-white"></lucide-icon>
            </div>
            <div>
              <h3 class="text-xl font-bold text-gray-900">Árboles Plantados</h3>
              <p class="text-sm text-gray-600">Progreso mensual</p>
            </div>
          </div>
          <div class="h-[350px]">
            <canvas baseChart
              [data]="monthlyChartData"
              [options]="monthlyChartOptions"
              [type]="monthlyChartType">
            </canvas>
          </div>
        </div>

        <!-- Residue Distribution -->
        <div class="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
          <div class="flex items-center gap-4 mb-6">
            <div class="w-12 h-12 bg-gradient-to-br from-[#0284c7] to-[#0ea5e9] rounded-2xl flex items-center justify-center">
              <lucide-icon name="recycle" class="w-6 h-6 text-white"></lucide-icon>
            </div>
            <div>
              <h3 class="text-xl font-bold text-gray-900">Distribución de Residuos</h3>
              <p class="text-sm text-gray-600">Por tipo de material</p>
            </div>
          </div>
          <div class="h-[350px]">
            <canvas baseChart
              [data]="residueChartData"
              [options]="residueChartOptions"
              [type]="residueChartType">
            </canvas>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Zone Activity & Volunteer Growth -->
  <section class="py-16" *ngIf="!isLoading">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="grid lg:grid-cols-2 gap-8">
        <!-- Zone Activity -->
        <div class="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
          <div class="flex items-center gap-4 mb-6">
            <div class="w-12 h-12 bg-gradient-to-br from-[#8b5cf6] to-[#a78bfa] rounded-2xl flex items-center justify-center">
              <lucide-icon name="map-pin" class="w-6 h-6 text-white"></lucide-icon>
            </div>
            <div>
              <h3 class="text-xl font-bold text-gray-900">Actividad por Zona</h3>
              <p class="text-sm text-gray-600">Reciclaje y reforestación</p>
            </div>
          </div>
          <div class="h-[350px]">
            <canvas baseChart
              [data]="zoneChartData"
              [options]="zoneChartOptions"
              [type]="zoneChartType">
            </canvas>
          </div>
        </div>

        <!-- Volunteer Growth -->
        <div class="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
          <div class="flex items-center gap-4 mb-6">
            <div class="w-12 h-12 bg-gradient-to-br from-[#f97316] to-[#fb923c] rounded-2xl flex items-center justify-center">
              <lucide-icon name="users" class="w-6 h-6 text-white"></lucide-icon>
            </div>
            <div>
              <h3 class="text-xl font-bold text-gray-900">Crecimiento de Voluntarios</h3>
              <p class="text-sm text-gray-600">Participación mensual</p>
            </div>
          </div>
          <div class="h-[350px]">
            <canvas baseChart
              [data]="volunteerChartData"
              [options]="volunteerChartOptions"
              [type]="volunteerChartType">
            </canvas>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Campaign vs Participants -->
  <section class="py-16 bg-gray-50" *ngIf="!isLoading">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
        <div class="flex items-center gap-4 mb-6">
          <div class="w-12 h-12 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-2xl flex items-center justify-center">
            <lucide-icon name="trending-up" class="w-6 h-6 text-white"></lucide-icon>
          </div>
          <div>
            <h3 class="text-xl font-bold text-gray-900">Campaña vs Participantes</h3>
            <p class="text-sm text-gray-600">Participación real por campaña registrada</p>
          </div>
        </div>
        <div class="h-[350px]">
          <canvas baseChart
            [data]="campaignChartData"
            [options]="campaignChartOptions"
            [type]="campaignChartType">
          </canvas>
        </div>
      </div>
    </div>
  </section>

  <!-- Cumulative Environmental Impact Section -->
  <section class="py-20 bg-gradient-to-br from-[#E8F5E9] to-[#C8E6C9]" *ngIf="!isLoading">
    <div class="max-w-7xl mx-auto px-6 lg:px-8">
      <div class="text-center mb-16">
        <h2 class="text-4xl font-bold text-gray-900 mb-4">Impacto Ambiental Acumulado</h2>
        <p class="text-lg text-gray-600">El resultado de nuestro esfuerzo colectivo</p>
      </div>

      <div class="grid md:grid-cols-3 gap-8">
        <div *ngFor="let card of impactCards" class="bg-white rounded-3xl p-8 shadow-xl hover:shadow-2xl transition-all hover:-translate-y-2">
          <div class="text-5xl font-bold text-[#2E7D32] mb-4">{{ card.value }}</div>
          <h3 class="text-xl font-bold text-gray-900 mb-2">{{ card.label }}</h3>
          <p class="text-gray-600">{{ card.detail }}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Loading State -->
  <ng-template #loadingState>
    <section class="py-16 bg-[#E8F5E9]">
      <div class="max-w-7xl mx-auto px-6 lg:px-8">
        <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <div *ngFor="let i of [1,2,3,4]" class="bg-white rounded-3xl p-8 shadow animate-pulse">
            <div class="w-16 h-16 bg-gray-200 rounded-2xl mb-6"></div>
            <div class="h-10 bg-gray-200 rounded w-3/4 mb-3"></div>
            <div class="h-4 bg-gray-200 rounded w-1/2"></div>
          </div>
        </div>
      </div>
    </section>
  </ng-template>
</main>

// src/pages/Statistics.tsx
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';
import { TreeDeciduous, Recycle, Users, TrendingUp } from 'lucide-react';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend, LineChart, Line } from 'recharts';

export default function Statistics() {
  const stats = [
    { icon: TreeDeciduous, label: 'Árboles Plantados', value: '15,432', change: '+1,234 este mes', color: 'from-[#2E7D32] to-[#4CAF50]' },
    { icon: Recycle, label: 'Kg Reciclados', value: '328,567', change: '+12,450 este mes', color: 'from-blue-500 to-blue-700' },
    { icon: Users, label: 'Voluntarios Activos', value: '1,856', change: '+142 este mes', color: 'from-purple-500 to-purple-700' },
    { icon: TrendingUp, label: 'Campañas Activas', value: '24', change: '+3 esta semana', color: 'from-orange-500 to-orange-700' },
  ];

  const monthlyTrees = [
    { month: 'Ene', arboles: 890 },
    { month: 'Feb', arboles: 1240 },
    { month: 'Mar', arboles: 1100 },
    { month: 'Abr', arboles: 1560 },
    { month: 'May', arboles: 1420 },
    { month: 'Jun', arboles: 1680 },
  ];

  const recyclingData = [
    { name: 'Plástico', value: 35, color: '#4CAF50' },
    { name: 'Papel', value: 25, color: '#2E7D32' },
    { name: 'Vidrio', value: 20, color: '#A5D6A7' },
    { name: 'Metal', value: 15, color: '#66BB6A' },
    { name: 'Orgánico', value: 5, color: '#81C784' },
  ];

  const zoneData = [
    { zone: 'Norte', reciclaje: 180, reforestacion: 45 },
    { zone: 'Sur', reciclaje: 145, reforestacion: 38 },
    { zone: 'Este', reciclaje: 95, reforestacion: 28 },
    { zone: 'Oeste', reciclaje: 120, reforestacion: 32 },
    { zone: 'Centro', reciclaje: 210, reforestacion: 52 },
  ];

  const participationData = [
    { month: 'Ene', voluntarios: 1420 },
    { month: 'Feb', voluntarios: 1580 },
    { month: 'Mar', voluntarios: 1650 },
    { month: 'Abr', voluntarios: 1720 },
    { month: 'May', voluntarios: 1790 },
    { month: 'Jun', voluntarios: 1856 },
  ];

  return (
    <div className="min-h-screen bg-white">
      <Header />

      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-[#2E7D32] to-[#1B5E20] text-white py-20">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="max-w-3xl">
            <div className="inline-block px-4 py-2 bg-white/20 backdrop-blur-sm rounded-full text-sm font-medium mb-6">
              📊 Estadísticas Ambientales
            </div>
            <h1 className="text-5xl font-bold mb-6">
              Nuestro impacto en números
            </h1>
            <p className="text-xl text-[#A5D6A7] mb-8">
              Visualiza el progreso colectivo de Cochabamba hacia un futuro más verde y sostenible.
            </p>
          </div>
        </div>
      </section>

      {/* Stats Cards */}
      <section className="py-16 bg-[#E8F5E9]">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {stats.map((stat, index) => {
              const Icon = stat.icon;
              return (
                <div key={index} className="bg-white rounded-3xl p-8 shadow-lg hover:shadow-2xl transition-all hover:-translate-y-1">
                  <div className={`w-16 h-16 bg-gradient-to-br ${stat.color} rounded-2xl flex items-center justify-center mb-6 shadow-lg`}>
                    <Icon className="w-8 h-8 text-white" />
                  </div>
                  <p className="text-4xl font-bold text-gray-900 mb-2">{stat.value}</p>
                  <p className="text-gray-600 font-medium mb-3">{stat.label}</p>
                  <p className="text-sm text-[#4CAF50] font-semibold">{stat.change}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Charts Section */}
      <section className="py-16">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-8 mb-8">
            {/* Trees Planted Monthly */}
            <div className="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-12 h-12 bg-gradient-to-br from-[#2E7D32] to-[#4CAF50] rounded-2xl flex items-center justify-center">
                  <TreeDeciduous className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900">Árboles Plantados</h3>
                  <p className="text-sm text-gray-600">Progreso mensual</p>
                </div>
              </div>
              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={monthlyTrees}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                  <XAxis dataKey="month" stroke="#6b7280" />
                  <YAxis stroke="#6b7280" />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: 'white',
                      border: '1px solid #e5e7eb',
                      borderRadius: '1rem',
                    }}
                  />
                  <Bar dataKey="arboles" fill="url(#colorGradient)" radius={[12, 12, 0, 0]} />
                  <defs>
                    <linearGradient id="colorGradient" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor="#4CAF50" />
                      <stop offset="100%" stopColor="#2E7D32" />
                    </linearGradient>
                  </defs>
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Recycling Distribution */}
            <div className="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
              <div className="flex items-center gap-4 mb-6">
                <div className="w-12 h-12 bg-gradient-to-br from-blue-500 to-blue-700 rounded-2xl flex items-center justify-center">
                  <Recycle className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h3 className="text-xl font-bold text-gray-900">Distribución de Residuos</h3>
                  <p className="text-sm text-gray-600">Por tipo de material</p>
                </div>
              </div>
              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={recyclingData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    outerRadius={100}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {recyclingData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Zone Activity */}
          <div className="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100 mb-8">
            <div className="flex items-center gap-4 mb-6">
              <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-purple-700 rounded-2xl flex items-center justify-center">
                <TrendingUp className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-gray-900">Actividad por Zona</h3>
                <p className="text-sm text-gray-600">Reciclaje y reforestación</p>
              </div>
            </div>
            <ResponsiveContainer width="100%" height={350}>
              <BarChart data={zoneData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                <XAxis dataKey="zone" stroke="#6b7280" />
                <YAxis stroke="#6b7280" />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'white',
                    border: '1px solid #e5e7eb',
                    borderRadius: '1rem',
                  }}
                />
                <Legend />
                <Bar dataKey="reciclaje" fill="#4CAF50" radius={[12, 12, 0, 0]} name="Kg Reciclados" />
                <Bar dataKey="reforestacion" fill="#2E7D32" radius={[12, 12, 0, 0]} name="Árboles Plantados" />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Volunteer Participation */}
          <div className="bg-white rounded-3xl p-8 shadow-lg border-2 border-gray-100">
            <div className="flex items-center gap-4 mb-6">
              <div className="w-12 h-12 bg-gradient-to-br from-orange-500 to-orange-700 rounded-2xl flex items-center justify-center">
                <Users className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-gray-900">Crecimiento de Voluntarios</h3>
                <p className="text-sm text-gray-600">Participación mensual</p>
              </div>
            </div>
            <ResponsiveContainer width="100%" height={350}>
              <LineChart data={participationData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
                <XAxis dataKey="month" stroke="#6b7280" />
                <YAxis stroke="#6b7280" />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'white',
                    border: '1px solid #e5e7eb',
                    borderRadius: '1rem',
                  }}
                />
                <Line 
                  type="monotone" 
                  dataKey="voluntarios" 
                  stroke="#4CAF50" 
                  strokeWidth={3}
                  dot={{ fill: '#2E7D32', strokeWidth: 2, r: 6 }}
                  name="Voluntarios Activos"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </section>

      {/* Impact Summary */}
      <section className="py-16 bg-gradient-to-br from-[#E8F5E9] to-[#C8E6C9]">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-4xl font-bold text-gray-900 mb-4">
              Impacto Ambiental Acumulado
            </h2>
            <p className="text-lg text-gray-600">
              El resultado de nuestro esfuerzo colectivo
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-white rounded-3xl p-8 text-center shadow-xl">
              <div className="text-6xl mb-4">🌳</div>
              <p className="text-5xl font-bold text-[#2E7D32] mb-2">15,432</p>
              <p className="text-gray-600 font-medium mb-4">Árboles plantados</p>
              <p className="text-sm text-gray-500">Equivalente a 185 hectáreas de bosque</p>
            </div>

            <div className="bg-white rounded-3xl p-8 text-center shadow-xl">
              <div className="text-6xl mb-4">♻️</div>
              <p className="text-5xl font-bold text-[#2E7D32] mb-2">328 ton</p>
              <p className="text-gray-600 font-medium mb-4">Residuos reciclados</p>
              <p className="text-sm text-gray-500">Reducción de 520 toneladas de CO₂</p>
            </div>

            <div className="bg-white rounded-3xl p-8 text-center shadow-xl">
              <div className="text-6xl mb-4">💧</div>
              <p className="text-5xl font-bold text-[#2E7D32] mb-2">2.4M L</p>
              <p className="text-gray-600 font-medium mb-4">Agua ahorrada</p>
              <p className="text-sm text-gray-500">Gracias al reciclaje de papel y plástico</p>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
